/**
 * e2e orchestrator — the ONLY supported way to run the suite.
 *
 *   npm run test:e2e            → full run (DB up → schema → seed → playwright → DB down)
 *   npm run test:e2e -- <args>  → args forwarded to `playwright test`
 *   npm run test:e2e:ui         → same but with --ui
 *
 * What it does, in order:
 *   1. Starts an EMBEDDED Postgres (binaries from the `embedded-postgres`
 *      npm package) on 127.0.0.1:54311 with its data dir under .e2e/ —
 *      fully isolated, no Docker, no system Postgres, no prod anywhere.
 *   2. `prisma db push` against that DB (this repo uses db push, not
 *      migrations — see prisma.config.ts) + `prisma generate` if needed.
 *   3. Seeds the fixture world (e2e/helpers/seed.ts).
 *   4. Writes .env.e2e (gitignored) documenting the test DB URL.
 *   5. Runs `playwright test` with the full test env (helpers/env.ts);
 *      Playwright's webServer boots `next dev` on :3105 with that env.
 *   6. Stops the embedded Postgres (data dir persists for fast re-runs).
 */
import { config as loadEnv } from "dotenv";
loadEnv(); // load repo-root .env so process.env.ANTHROPIC_API_KEY is set before helpers/env reads it

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import EmbeddedPostgres from "embedded-postgres";
import { E2E, E2E_DB_URL, REPO_ROOT, assertSafeTestDbUrl, buildTestEnv } from "./helpers/env";

function run(cmd: string, args: string[], env: Record<string, string>): Promise<number> {
  return new Promise((resolve, reject) => {
    const child = spawn(cmd, args, {
      cwd: REPO_ROOT,
      stdio: "inherit",
      env: { ...process.env, ...env },
    });
    child.on("error", reject);
    child.on("exit", (code) => resolve(code ?? 1));
  });
}

async function main(): Promise<number> {
  assertSafeTestDbUrl(E2E_DB_URL);
  mkdirSync(path.dirname(E2E.DATA_DIR), { recursive: true });

  // Document the URL for humans / ad-hoc psql (gitignored).
  writeFileSync(
    path.join(REPO_ROOT, ".env.e2e"),
    `# Generated by e2e/run.ts — ISOLATED local test database (embedded Postgres).\n` +
      `# Never points at prod. Safe to delete; recreated on every run.\n` +
      `DATABASE_URL=${E2E_DB_URL}\nDIRECT_URL=${E2E_DB_URL}\n`,
  );

  const pg = new EmbeddedPostgres({
    databaseDir: E2E.DATA_DIR,
    user: E2E.DB_USER,
    password: E2E.DB_PASSWORD,
    port: E2E.DB_PORT,
    persistent: true,
    onLog: () => {},
    onError: () => {},
  });

  const freshCluster = !existsSync(path.join(E2E.DATA_DIR, "PG_VERSION"));
  if (freshCluster) {
    console.log("[e2e] initialising embedded Postgres cluster…");
    await pg.initialise();
  }
  console.log(`[e2e] starting embedded Postgres on 127.0.0.1:${E2E.DB_PORT}…`);
  let weStartedPg = true;
  try {
    await pg.start();
  } catch (err) {
    // A previous run may have left the cluster up (crash). Try to reuse it.
    console.warn("[e2e] start failed — checking for an already-running test cluster…", err);
    weStartedPg = false;
    const probe = pg.getPgClient("postgres");
    await probe.connect();
    await probe.end();
    console.log("[e2e] reusing the already-running embedded cluster.");
  }

  try {
    // Ensure the test database exists.
    const client = pg.getPgClient("postgres");
    await client.connect();
    const existsRes = await client.query(`SELECT 1 FROM pg_database WHERE datname = $1`, [E2E.DB_NAME]);
    if (existsRes.rowCount === 0) {
      await client.query(`CREATE DATABASE ${E2E.DB_NAME}`);
      console.log(`[e2e] created database ${E2E.DB_NAME}`);
    }
    await client.end();

    const dbEnv = { DATABASE_URL: E2E_DB_URL, DIRECT_URL: E2E_DB_URL };

    // Prisma client (src/generated/prisma) — generate if missing.
    if (!existsSync(path.join(REPO_ROOT, "src", "generated", "prisma"))) {
      console.log("[e2e] generating Prisma client…");
      const gen = await run("npx", ["prisma", "generate"], dbEnv);
      if (gen !== 0) return gen;
    }

    console.log("[e2e] applying schema (prisma db push)…");
    const push = await run("npx", ["prisma", "db", "push"], dbEnv);
    if (push !== 0) return push;

    console.log("[e2e] seeding fixture world…");
    const seedCode = await run("npx", ["tsx", "e2e/helpers/seed-cli.ts"], {
      MT_E2E_DATABASE_URL: E2E_DB_URL,
    });
    if (seedCode !== 0) return seedCode;

    console.log("[e2e] running Playwright…");
    const pwArgs = ["playwright", "test", ...process.argv.slice(2)];
    return await run("npx", pwArgs, { ...buildTestEnv(), MT_E2E: "1" });
  } finally {
    if (weStartedPg) {
      console.log("[e2e] stopping embedded Postgres…");
      await pg.stop().catch(() => {});
    }
  }
}

main().then(
  (code) => process.exit(code),
  (err) => {
    console.error("[e2e] fatal:", err);
    process.exit(1);
  },
);
